import type { Writer } from "$writers";
import type { Variable } from "$ast";

export class EnvarWriter implements Writer {
  writeHeader(prev: string): string {
    return prev + `import {
  initVariable,
  REQUIRED,
  OPTIONAL,
} from "jsr:@wuespace/envar";
 
/**
 * Initializes the environment variables using the jsr:@wuespace/envar library.
 * 
 * Automatically generated by [envardoc](https://jsr.io/@wuespace/envardoc).
 */
export function initEnv(): Promise<void> {
  return Promise.all([
`;
  }

  writeVariable(variable: Variable, prev: string): string {
    variable.description?.trim().split("\n").forEach((line) => {
      prev += `    // ${line}\n`;
    });
    if (variable.optional) {
      return this.writeOptionalVariable(variable, prev) + "\n";
    } else {
      return this.writeRequiredVariable(variable, prev) + "\n";
    }
  }

  private writeOptionalVariable(variable: Variable, prev: string): string {
    prev += '    initVariable("';
    prev += variable.name;
    prev += '", OPTIONAL';
    if (variable.defaultValue) {
      prev += ', "';
      prev += variable.defaultValue;
      prev += '"';
    }
    prev += "),\n";
    return prev;
  }

  private writeRequiredVariable(variable: Variable, prev: string): string {
    prev += '    initVariable("';
    prev += variable.name;
    prev += '", REQUIRED),\n';
    return prev;
  }

  writeFooter(prev: string): string {
    return prev.trimEnd() + `\n  ]).then(/* convert to Promise<void> */);
}
`;
  }
}
