name: Publish on JSR
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: npx jsr publish
      - name: Setup Deno Environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Test that things are working
        run: deno task run
      - name: Publish to JSR
        run: deno publish
