name: Release Automation (triggered on tag)

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+

jobs:
  test-deno:
    runs-on: ubuntu-latest
    name: Test the Deno CLI
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run the CLI to verify it's working
        run: deno task run
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    needs: test-deno
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Update version in `deno.json`
        run: |
          tag=${GITHUB_REF#refs/tags/}
          version=${tag#v}
          jq --arg version "$version" '.version = $version' deno.json > tmp.$$.json
          mv tmp.$$.json deno.json
      - name: Publish to JSR
        run: deno publish --allow-dirty --dry-run
